<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />

  <PropertyGroup>
    <IsAotCompatible>false</IsAotCompatible>
    <IsTrimmable>false</IsTrimmable>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors></WarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
